#!/usr/bin/env bash

set -e

while getopts r:u:t: option
do
case "${option}"
in
r) RELEASE=${OPTARG};;
u) URL=${OPTARG};;
t) TOKEN=${OPTARG};;
esac
done

[[ -z "$RELEASE" ]] && { echo "Please specify a release tag, e.g., -r v1.0.0" ; exit 1; }
[[ -z "$URL" ]] && { echo "Please specify a public host URL, e.g., -u https://mycafe.com" ; exit 1; }
[[ -z "$TOKEN" ]] && { echo "Please specify a cafe access token, e.g., -t 2GE5YWVqE...rVsncZt" ; exit 1; }

# install
wget https://github.com/textileio/go-textile/releases/download/"$RELEASE"/go-textile_"$RELEASE"_linux-amd64.tar.gz
tar xvfz go-textile_"$RELEASE"_linux-amd64.tar.gz
rm go-textile_"$RELEASE"_linux-amd64.tar.gz
sudo ./install

# init
textile init -s $(textile wallet init | tail -n1) --server --cafe-open --cafe-url="$URL" --cafe-bind-addr=0.0.0.0:40601 --gateway-bind-addr=0.0.0.0:5050 --swarm-ports=4001

# textile systemctl service
sudo bash -c 'cat >/lib/systemd/system/textile.service <<EOL
[Unit]
Description=textile
[Service]
ExecStart=/usr/local/bin/textile daemon
Restart=always
User=ec2-user
Group=ec2-user
LimitNPROC=32768
LimitNOFILE=65536
Environment="IPFS_FD_MAX=65536"
[Install]
WantedBy=multi-user.target
EOL'

# enable the new services
sudo systemctl daemon-reload
sudo systemctl enable textile.service
sudo systemctl start textile

# echo new node info
sleep 5
echo $(textile version --git)
echo "peerID:" $(textile ipfs id)
echo "address:" $(textile account address)

textile tokens create --token="$TOKEN"
echo "token added"
